Add support for transformation max depths
spatie/laravel-data pull request #699
Opened 2024-03-13 10:53 UTC by rubenvanassche

2024-03-13 11:00 UTC, sebastiandedeyne requested changes

2024-03-13 11:02 UTC, rubenvanassche commented on config/data.php
> +    'fail_when_max_transformation_depth_reached' => true,
Jup

2024-03-13 11:02 UTC, rubenvanassche commented on src/Resolvers/TransformedDataResolver.php
> +    use ChecksTransformationDepths;
It needs to be somewhere, also makes it easy for other people who want to build casts based upon max depth checks to include it.

2024-03-13 11:09 UTC, merged

2024-03-13 19:34 UTC, inmanturbo commented
@rubenvanassche 
It looks like this broke some packages that depend on laravel-data.
```
Spatie\LaravelData\Support\Transformation\TransformationContext::__construct(): Argument #11 ($throwWhenMaxDepthReached) must be of type bool, null given
```
It looks like updating the config to include ` 'throw_when_max_transformation_depth_reached' => true,` will probably fix it at the app level, but I'm not sure how to fix the packages' ci.

Any advice?

2024-03-13 19:44 UTC, inmanturbo commented
for now I'm adding 

```php
config()->set('data.throw_when_max_transformation_depth_reached', true);
```
to `getEnvironmentSetUp()` in the test case and it seems to work but it feels strange to have to explicitly set the config for a dependency to its default value. These packages don't have any published laravel-data configuration nor do they interact with its config.

2024-04-04 10:20 UTC, rubenvanassche commented
See the answer here: https://github.com/spatie/laravel-data/issues/731